alias upup="sudo apt -y update && sudo apt -y upgrade && sudo apt -y dist-upgrade && sudo apt -y autoclean && sudo apt -y autoremove"
alias gitlog="git log --decorate --oneline --all --graph"
alias act="source activate"
alias deact="source deactivate"
alias sizeof="du -sh"
