alias act="conda activate"
alias deact="conda deactivate"
alias gitlog="git log --decorate --oneline --all --graph"
alias lr="ls -latrh"
alias size="du -bhs * | sort -h"
alias upup="sudo apt -y update && sudo apt -y upgrade && sudo apt -y dist-upgrade && sudo apt -y autoclean && sudo apt -y autoremove"